flows:
  default:
    description: run tests, type-checking, and docs dev server
    nodes:
      tests:
        recipe: tests
        triggers:
        - code-changes
      types:
        recipe: types
        triggers:
        - code-changes
      docs:
        recipe: docs
        triggers:
        - delay: 1
        - watch: ["docs/hooks/"]

recipes:
  tests:
    commands: |
      pytest -vv --cov

  types:
    commands: |
      mypy

  docs:
    commands: |
      mkdocs serve --strict

triggers:
  code-changes:
    watch:
    - src/
    - tests/
    - docs/examples/
    - docs/hooks/
    - pyproject.toml
    - .coveragerc
