flows:
  default:
    nodes:
      tests:
        target: tests
        triggers:
        - code-changes
      types:
        target: types
        triggers:
        - code-changes
      docs:
        target: docs
        triggers:
        - delay: 1
        - paths:
          - docs/hooks/

targets:
  tests:
    commands: |
      pytest -vv --cov

  types:
    commands: |
      mypy

  docs:
    commands: |
      mkdocs serve --strict

triggers:
  code-changes:
    type: watch
    paths:
    - synthesize/
    - tests/
    - docs/examples/
    - pyproject.toml
    - .coveragerc
