flows:
  default:
    nodes:
      tests:
        target: tests
        trigger: code-changes
      types:
        target: types
        trigger: code-changes
      docs:
        target: docs
        trigger:
          type: restart

targets:
  tests:
    commands: |
      pytest -vv --cov

  types:
    commands: |
      mypy

  docs:
    commands: |
      mkdocs serve --strict

triggers:
  code-changes:
    type: watch
    paths:
      - synthesize/
      - tests/
      - docs/examples/
      - pyproject.toml
      - .coveragerc
