name: publish-package

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7
    - name: Set up Python 3.x
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.x"
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
    - name: Build the package
      run: poetry build -vvv
    - name: Publish to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.pypi_token }}
      working-directory: ${{ github.workspace }}
